-- Generated by scripts/generate-cms-seed.ts. Do not hand-edit.
--> statement-breakpoint
-- Migrated static content intentionally has NULL actor ids; all interactive CMS writes require a real actor.
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:getting-started','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:getting-started:en:v1','seed:docs:getting-started','en',1,'getting-started','Getting started','Publish a source request and understand the SourceBoard workflow.','## Create a source request

Start with one image and a focused question. Add the context you already know instead of guessing at a creator or origin.

- Choose the correct visibility before publishing.
- Mark sensitive imagery accurately.
- Keep the title specific enough that people can investigate the same question.

## Follow the evidence trail

Comments can contribute candidate sources, context and links. A useful source answer should make it possible for another person to verify the claim independently.

## Resolve the request

The post author may accept a source when the evidence answers the request. SourceBoard records that Accepted Source separately from later verification or moderation state.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:getting-started','en','PUBLISHED','seed:docs:getting-started:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:getting-started:route:en:getting-started','seed:docs:getting-started','en','DOCS','getting-started',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:getting-started:nav:docs','seed:docs:getting-started','DOCS','Using SourceBoard',0,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:getting-started:nav:docs','en','Getting started');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:accepted-sources','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:accepted-sources:en:v1','seed:docs:accepted-sources','en',1,'accepted-sources','Accepted Sources','How source acceptance, verification, disputes and provenance differ.','## What Accepted Source means

Accepted Source records the post author''s selected answer to a source request. It does not transfer copyright, establish legal ownership or make every statement in a comment independently verified.

## Verification is a separate state

Source Integrity review can add verification, dispute or revoke a resolution when evidence changes. The audit trail preserves the history instead of silently rewriting it.

## Public provenance

For public posts, SourceBoard exposes structured information so crawlers and automated systems can distinguish the request image, public author, accepted source URL, evidence and status. Private account data is not part of that public provenance surface.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:accepted-sources','en','PUBLISHED','seed:docs:accepted-sources:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:accepted-sources:route:en:accepted-sources','seed:docs:accepted-sources','en','DOCS','accepted-sources',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:accepted-sources:nav:docs','seed:docs:accepted-sources','DOCS','Using SourceBoard',1,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:accepted-sources:nav:docs','en','Accepted Sources');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:accepted-sources:nav:footer','seed:docs:accepted-sources','FOOTER','Product',0,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:accepted-sources:nav:footer','en','Accepted Sources');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:comments','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:comments:en:v1','seed:docs:comments','en',1,'comments','Comments and discussion','Replies, source leads, reactions, media and closed discussions.','## Add useful context

Comments support Markdown, source links and eligible media. Prefer information that advances the source trail over speculation or repeated guesses.

## Closed comments

After a source has been accepted, the post author can close comments. Existing discussion remains visible, while the server rejects new comments until the author reopens the discussion when that action is available.

## Editing, deletion and moderation

Edits and deletes update the visible discussion without requiring a manual page refresh. Moderated or removed content may retain internal audit data even when it is no longer publicly visible.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:comments','en','PUBLISHED','seed:docs:comments:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:comments:route:en:comments','seed:docs:comments','en','DOCS','comments',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:comments:nav:docs','seed:docs:comments','DOCS','Using SourceBoard',2,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:comments:nav:docs','en','Comments and discussion');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:friends','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:friends:en:v1','seed:docs:friends','en',1,'friends','Friends and discovery','Requests, accepted friends, discovery, blocks and profile privacy.','## Friend requests

Friend requests are private account state. Incoming and outgoing requests stay separate until accepted, and a user can disable new requests through supported privacy settings.

## Friendship does not override privacy

Server-side policy still decides whether a viewer can access a profile or friends-only content. Blocking takes precedence over friendship and discovery surfaces.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:friends','en','PUBLISHED','seed:docs:friends:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:friends:route:en:friends','seed:docs:friends','en','DOCS','friends',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:friends:nav:docs','seed:docs:friends','DOCS','Social',3,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:friends:nav:docs','en','Friends and discovery');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:store-and-points','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:store-and-points:en:v1','seed:docs:store-and-points','en',1,'store-and-points','Store, points and contributions','How points are earned, protected from farming and spent on cosmetics.','## Earn points through participation

SourceBoard awards bounded points for useful interactions such as source requests, comments, eligible likes, friendship actions and one-time profile completion. Accepted and Verified Source rewards use separate versioned rules.

- Post: 3 points, up to 5 rewarded posts per day.
- Comment: 2 points, up to 15 rewarded comments per day.
- Eligible post/comment like: 1 point, with daily caps and no self-like reward.
- Profile avatar, bio and first public social link: one-time completion rewards.
- Share action: a bounded share-intent reward, not proof that an external share was published or viewed.

## Anti-abuse rules

Rewards use server-generated amounts, deterministic idempotency keys and daily limits. Repeating the same like, removing and re-adding the same friend, retrying a request or toggling profile fields cannot farm the same reward.

When rewarded posts or comments are deleted, SourceBoard appends a reversal to the ledger instead of modifying historical entries.

## Spend and equip

Store items may cost points or be Free. Global emote packs are available without individual ownership rows. Cosmetic equipment is separate from ownership, so unequipping an item does not remove it from inventory.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:store-and-points','en','PUBLISHED','seed:docs:store-and-points:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:store-and-points:route:en:store-and-points','seed:docs:store-and-points','en','DOCS','store-and-points',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:store-and-points:nav:docs','seed:docs:store-and-points','DOCS','Account and personalization',4,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:store-and-points:nav:docs','en','Store, points and contributions');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:store-and-points:nav:footer','seed:docs:store-and-points','FOOTER','Product',1,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:store-and-points:nav:footer','en','Store, points and contributions');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:account-verification','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:account-verification:en:v1','seed:docs:account-verification','en',1,'account-verification','Account and email verification','Registration, Google sign-in, Firebase email verification and sessions.','## Registration security

Registration uses Cloudflare Turnstile and server-side validation. Security checks are part of the authentication flow rather than decorative client-only controls.

## Firebase verification handoff

When Firebase verifies an email, SourceBoard synchronizes that verified identity instead of requiring an unrelated second verification. Verification links may return with Firebase''s oobCode and continue through the SourceBoard handoff.

## Sessions

Sessions are server-managed and can be invalidated by account security or moderation actions. Signing out ends the current browser session; supported security controls may end other sessions as well.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:account-verification','en','PUBLISHED','seed:docs:account-verification:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:account-verification:route:en:account-verification','seed:docs:account-verification','en','DOCS','account-verification',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:account-verification:nav:docs','seed:docs:account-verification','DOCS','Account and personalization',5,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:account-verification:nav:docs','en','Account and email verification');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:account-verification:nav:footer','seed:docs:account-verification','FOOTER','Product',2,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:account-verification:nav:footer','en','Account and email verification');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:moderation-and-reports','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:moderation-and-reports:en:v1','seed:docs:moderation-and-reports','en',1,'moderation-and-reports','Moderation and reports','Reporting content, sanctions, Source Integrity and administrative audit trails.','## Report content

Use the report action for spam, harassment, misleading sources, sensitive content, privacy issues, copyright concerns or other policy problems. Reports are reviewed separately from public discussion.

## Moderation actions

Administrative actions can include posting/comment restrictions, suspension, bans, role changes, session invalidation and account handling. Strong actions require server-side capability checks and an audit reason.

## Source Integrity

Accepted Sources can be reviewed as accepted, disputed, suspicious, verified or revoked without collapsing those states into a separate competing verification system.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:moderation-and-reports','en','PUBLISHED','seed:docs:moderation-and-reports:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:moderation-and-reports:route:en:moderation-and-reports','seed:docs:moderation-and-reports','en','DOCS','moderation-and-reports',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:moderation-and-reports:nav:docs','seed:docs:moderation-and-reports','DOCS','Safety and support',6,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:moderation-and-reports:nav:docs','en','Moderation and reports');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:troubleshooting','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:troubleshooting:en:v1','seed:docs:troubleshooting','en',1,'troubleshooting','Troubleshooting','Common account, media, Store and stale-interface problems.','## Login or registration does not complete

Confirm that the Cloudflare security check loaded and that cookies are allowed for SourceBoard. If an old tab has stale security state, retry the form from the current page rather than reusing an old submission.

## Firebase says verified but SourceBoard does not

Return to SourceBoard and sign in with the same identity. The login flow synchronizes Firebase verification state. Do not submit a separate legacy token unless the link actually contains one.

## A change appears stale

SourceBoard mutations are designed to reconcile locally or revalidate the current route. If a current production build still requires a manual refresh after a successful mutation, report the page and action because that is treated as a product defect.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:troubleshooting','en','PUBLISHED','seed:docs:troubleshooting:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:troubleshooting:route:en:troubleshooting','seed:docs:troubleshooting','en','DOCS','troubleshooting',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:troubleshooting:nav:docs','seed:docs:troubleshooting','DOCS','Safety and support',7,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:troubleshooting:nav:docs','en','Troubleshooting');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:legal:terms','LEGAL',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:legal:terms:en:v1','seed:legal:terms','en',1,'terms','Terms of Use','Baseline terms for using SourceBoard and contributing public content.','## Using the service

Use SourceBoard only in ways permitted by applicable law and these product policies. Features, limits and availability can change as the service evolves.

## Your contributions

You remain responsible for content you submit and for having the rights or lawful basis needed to submit it. SourceBoard''s source-resolution labels do not grant ownership of third-party work.

## Enforcement

SourceBoard may restrict or remove access when needed to enforce product rules, protect users or operate the service. This summary is product documentation and should receive legal review before being treated as final contractual text.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:legal:terms','en','PUBLISHED','seed:legal:terms:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:legal:terms:route:en:terms','seed:legal:terms','en','LEGAL','terms',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:terms:nav:docs','seed:legal:terms','DOCS','Policies',8,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:terms:nav:docs','en','Terms of Use');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:terms:nav:footer','seed:legal:terms','FOOTER','Policies',3,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:terms:nav:footer','en','Terms of Use');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:legal:privacy','LEGAL',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:legal:privacy:en:v1','seed:legal:privacy','en',1,'privacy','Privacy','What SourceBoard keeps private and what becomes public when you publish.','## Public information

Public profiles, public source requests, visible comments and public source-resolution metadata can be delivered to visitors and crawlers. The interface should make the relevant visibility choice clear before publication.

## Private account data

Email addresses, sessions, moderation notes, administrative data, private or friends-only content and non-public profile information are not intentionally exposed through public pages, sitemaps or structured public metadata.

## Privacy controls

Supported settings govern profile visibility, friend requests, sensitive-content presentation, blocks and other product privacy choices. This page describes current product behavior and requires legal review for jurisdiction-specific privacy obligations.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:legal:privacy','en','PUBLISHED','seed:legal:privacy:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:legal:privacy:route:en:privacy','seed:legal:privacy','en','LEGAL','privacy',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:privacy:nav:docs','seed:legal:privacy','DOCS','Policies',9,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:privacy:nav:docs','en','Privacy');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:privacy:nav:footer','seed:legal:privacy','FOOTER','Policies',4,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:privacy:nav:footer','en','Privacy');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:legal:community-guidelines','LEGAL',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:legal:community-guidelines:en:v1','seed:legal:community-guidelines','en',1,'community-guidelines','Community Guidelines','Rules for useful, safe source-finding discussions.','## Prefer evidence over certainty

Do not present an uncertain attribution as established fact. Explain how a link, creator identity or publication relates to the request and correct mistakes when better evidence appears.

## Respect people

Do not use SourceBoard for harassment, threats, targeted abuse, doxxing, impersonation, spam or attempts to expose private personal information.

## Moderation

Report policy violations instead of escalating them in comments. Moderation decisions and Source Integrity decisions can use separate review and audit trails.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:legal:community-guidelines','en','PUBLISHED','seed:legal:community-guidelines:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:legal:community-guidelines:route:en:community-guidelines','seed:legal:community-guidelines','en','LEGAL','community-guidelines',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:community-guidelines:nav:docs','seed:legal:community-guidelines','DOCS','Policies',10,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:community-guidelines:nav:docs','en','Community Guidelines');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:community-guidelines:nav:footer','seed:legal:community-guidelines','FOOTER','Policies',5,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:community-guidelines:nav:footer','en','Community Guidelines');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:legal:acceptable-use','LEGAL',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:legal:acceptable-use:en:v1','seed:legal:acceptable-use','en',1,'acceptable-use','Acceptable Use','Prohibited abuse of SourceBoard accounts, automation and infrastructure.','## Do not abuse the service

Do not bypass rate limits, security checks, access controls or moderation restrictions. Do not automate interactions primarily to farm points, manipulate engagement or overwhelm other users or infrastructure.

## Security

Do not probe for private data, attempt unauthorized account access, upload malicious payloads or use SourceBoard to distribute malware or deceptive links.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:legal:acceptable-use','en','PUBLISHED','seed:legal:acceptable-use:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:legal:acceptable-use:route:en:acceptable-use','seed:legal:acceptable-use','en','LEGAL','acceptable-use',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:acceptable-use:nav:docs','seed:legal:acceptable-use','DOCS','Policies',11,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:acceptable-use:nav:docs','en','Acceptable Use');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:acceptable-use:nav:footer','seed:legal:acceptable-use','FOOTER','Policies',6,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:acceptable-use:nav:footer','en','Acceptable Use');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:legal:copyright-and-attribution','LEGAL',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:legal:copyright-and-attribution:en:v1','seed:legal:copyright-and-attribution','en',1,'copyright-and-attribution','Copyright, DMCA and attribution','How source attribution relates to copyright and removal requests.','## Attribution is not ownership

Accepted Source and verification labels are provenance tools. They do not transfer copyright, create a license or replace the rights of the original creator.

## Copyright concerns

SourceBoard should provide a documented process for copyright or takedown requests and preserve enough internal information to investigate them. The final notice-and-takedown procedure, designated contacts and jurisdiction-specific language require legal review before launch.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:legal:copyright-and-attribution','en','PUBLISHED','seed:legal:copyright-and-attribution:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:legal:copyright-and-attribution:route:en:copyright-and-attribution','seed:legal:copyright-and-attribution','en','LEGAL','copyright-and-attribution',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:copyright-and-attribution:nav:docs','seed:legal:copyright-and-attribution','DOCS','Policies',12,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:copyright-and-attribution:nav:docs','en','Copyright, DMCA and attribution');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:copyright-and-attribution:nav:footer','seed:legal:copyright-and-attribution','FOOTER','Policies',7,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:copyright-and-attribution:nav:footer','en','Copyright, DMCA and attribution');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:legal:data-handling','LEGAL',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:legal:data-handling:en:v1','seed:legal:data-handling','en',1,'data-handling','Data Handling','Operational storage, private media and account-data boundaries.','## Service data

SourceBoard stores the account, profile, post, comment, relationship, Store, audit and moderation records needed to operate supported features. D1 remains authoritative for application state.

## Media

Uploaded media is stored in object storage and delivered through SourceBoard routes according to the relevant access policy. Private media should not be converted into publicly enumerable object URLs.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:legal:data-handling','en','PUBLISHED','seed:legal:data-handling:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:legal:data-handling:route:en:data-handling','seed:legal:data-handling','en','LEGAL','data-handling',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:data-handling:nav:docs','seed:legal:data-handling','DOCS','Policies',13,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:data-handling:nav:docs','en','Data Handling');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:data-handling:nav:footer','seed:legal:data-handling','FOOTER','Policies',8,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:data-handling:nav:footer','en','Data Handling');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:legal:ai-public-content','LEGAL',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:legal:ai-public-content:en:v1','seed:legal:ai-public-content','en',1,'ai-public-content','AI and public content','How public SourceBoard pages are made understandable to crawlers and automated systems.','## Machine-readable public pages

Public posts can include semantic HTML, canonical URLs, structured metadata, sitemaps and explicit Accepted Source provenance so search engines and automated systems can understand the public source trail.

## No training promise

Making public content crawlable does not mean SourceBoard can promise that Google, OpenAI or any other external system will index, use or train on a particular page. External systems make their own decisions under their own policies.

## Private data stays out of the public surface

Emails, sessions, moderation notes, admin data, private profiles, friends-only posts and hidden comments are excluded from the intended public crawler and structured-data surface.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:legal:ai-public-content','en','PUBLISHED','seed:legal:ai-public-content:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:legal:ai-public-content:route:en:ai-public-content','seed:legal:ai-public-content','en','LEGAL','ai-public-content',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:ai-public-content:nav:docs','seed:legal:ai-public-content','DOCS','Policies',14,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:ai-public-content:nav:docs','en','AI and public content');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:legal:ai-public-content:nav:footer','seed:legal:ai-public-content','FOOTER','Policies',9,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:legal:ai-public-content:nav:footer','en','AI and public content');
--> statement-breakpoint
INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES ('seed:docs:support','DOCS',NULL,0,0);
--> statement-breakpoint
INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES ('seed:docs:support:en:v1','seed:docs:support','en',1,'support','Help and support','What to include when reporting a SourceBoard product problem.','## Report a product problem

Include the page, the action you attempted, what you expected and what actually happened. For visual defects, a screenshot and viewport size are especially useful. Do not include passwords, session cookies or authentication tokens.

## Account or safety issue

Use in-product reporting for content or conduct issues when available. Account-security and privacy incidents should be handled through a dedicated support path before public launch; final contact details still need operational and legal review.',NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES ('seed:docs:support','en','PUBLISHED','seed:docs:support:en:v1',0,NULL,0);
--> statement-breakpoint
INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES ('seed:docs:support:route:en:support','seed:docs:support','en','DOCS','support',1,0);
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:support:nav:docs','seed:docs:support','DOCS','Safety and support',15,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:support:nav:docs','en','Help and support');
--> statement-breakpoint
INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES ('seed:docs:support:nav:footer','seed:docs:support','FOOTER','Product',10,1,0,0);
--> statement-breakpoint
INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES ('seed:docs:support:nav:footer','en','Help and support');
