import { writeFileSync } from "node:fs";
import { DOCS_ARTICLES, type DocsArticle } from "../app/data/docs-content";

const FOOTER_SLUGS = new Set([
  "support",
  "accepted-sources",
  "store-and-points",
  "terms",
  "privacy",
  "community-guidelines",
  "acceptable-use",
  "copyright-and-attribution",
  "data-handling",
  "ai-public-content",
  "account-verification",
]);

function sql(value: string | null): string {
  if (value === null) return "NULL";
  return `'${value.replaceAll("'", "''")}'`;
}

function markdown(article: DocsArticle): string {
  const blocks: string[] = [];
  for (const section of article.sections) {
    blocks.push(`## ${section.title}`);
    blocks.push(...section.paragraphs);
    if (section.bullets?.length) blocks.push(section.bullets.map((item) => `- ${item}`).join("\n"));
  }
  return blocks.join("\n\n");
}

function namespaceFor(article: DocsArticle): "DOCS" | "LEGAL" {
  return article.kind === "policy" ? "LEGAL" : "DOCS";
}

function pageId(article: DocsArticle): string {
  return `seed:${namespaceFor(article).toLowerCase()}:${article.slug}`;
}

function revisionId(article: DocsArticle): string {
  return `${pageId(article)}:en:v1`;
}

function routeId(article: DocsArticle): string {
  return `${pageId(article)}:route:en:${article.slug}`;
}

function navId(article: DocsArticle, surface: "DOCS" | "FOOTER"): string {
  return `${pageId(article)}:nav:${surface.toLowerCase()}`;
}

export function generateCmsSeedSql(): string {
  const out = [
    "-- Generated by scripts/generate-cms-seed.ts. Do not hand-edit.",
    "-- Migrated static content intentionally has NULL actor ids; all interactive CMS writes require a real actor.",
  ];
  let docsOrder = 0;
  let footerOrder = 0;
  for (const article of DOCS_ARTICLES) {
    const id = pageId(article);
    const revision = revisionId(article);
    const namespace = namespaceFor(article);
    out.push(
      `INSERT INTO cms_pages (id,namespace,created_by_user_id,created_at,updated_at) VALUES (${sql(id)},${sql(namespace)},NULL,0,0);`,
      `INSERT INTO cms_page_revisions (id,page_id,locale,version,slug,title,description,body_markdown,created_by_user_id,created_at) VALUES (${sql(revision)},${sql(id)},'en',1,${sql(article.slug)},${sql(article.title)},${sql(article.summary)},${sql(markdown(article))},NULL,0);`,
      `INSERT INTO cms_page_locale_state (page_id,locale,status,published_revision_id,published_at,published_by_user_id,updated_at) VALUES (${sql(id)},'en','PUBLISHED',${sql(revision)},0,NULL,0);`,
      `INSERT INTO cms_page_routes (id,page_id,locale,namespace,slug,is_current,created_at) VALUES (${sql(routeId(article))},${sql(id)},'en',${sql(namespace)},${sql(article.slug)},1,0);`,
      `INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES (${sql(navId(article, "DOCS"))},${sql(id)},'DOCS',${sql(article.group)},${docsOrder++},1,0,0);`,
      `INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES (${sql(navId(article, "DOCS"))},'en',${sql(article.title)});`,
    );
    if (FOOTER_SLUGS.has(article.slug)) {
      out.push(
        `INSERT INTO cms_navigation_items (id,page_id,surface,group_key,sort_order,is_visible,created_at,updated_at) VALUES (${sql(navId(article, "FOOTER"))},${sql(id)},'FOOTER',${sql(article.kind === "policy" ? "Policies" : "Product")},${footerOrder++},1,0,0);`,
        `INSERT INTO cms_navigation_labels (navigation_item_id,locale,label) VALUES (${sql(navId(article, "FOOTER"))},'en',${sql(article.title)});`,
      );
    }
  }
  return `${out.join("\n--> statement-breakpoint\n")}\n`;
}

const output = generateCmsSeedSql();
const stdout = process.argv.includes("--stdout");
if (stdout) {
  process.stdout.write(output);
} else {
  writeFileSync(new URL("../migrations/0034_cms_seed_existing_content.sql", import.meta.url), output);
}
